package androidx.leanback;

import com.motorola.systemui.desk.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class R$styleable {
    public static final int LeanbackGuidedStepTheme_guidedStepKeyline = 46;
    public static final int PagingIndicator_arrowBgColor = 0;
    public static final int PagingIndicator_arrowColor = 1;
    public static final int PagingIndicator_arrowRadius = 2;
    public static final int PagingIndicator_dotBgColor = 3;
    public static final int PagingIndicator_dotToArrowGap = 4;
    public static final int PagingIndicator_dotToDotGap = 5;
    public static final int PagingIndicator_lbDotRadius = 6;
    public static final int lbBaseCardView_Layout_layout_viewType = 0;
    public static final int lbBaseCardView_activatedAnimationDuration = 0;
    public static final int lbBaseCardView_cardBackground = 1;
    public static final int lbBaseCardView_cardForeground = 2;
    public static final int lbBaseCardView_cardType = 3;
    public static final int lbBaseCardView_extraVisibility = 4;
    public static final int lbBaseCardView_infoVisibility = 5;
    public static final int lbBaseCardView_selectedAnimationDelay = 6;
    public static final int lbBaseCardView_selectedAnimationDuration = 7;
    public static final int lbDatePicker_android_maxDate = 1;
    public static final int lbDatePicker_android_minDate = 0;
    public static final int lbDatePicker_datePickerFormat = 2;
    public static final int lbImageCardView_infoAreaBackground = 0;
    public static final int lbImageCardView_lbImageCardViewType = 1;
    public static final int lbPicker_pickerItemLayout = 0;
    public static final int lbPicker_pickerItemTextViewId = 1;
    public static final int lbPinPicker_columnCount = 0;
    public static final int lbResizingTextView_maintainLineSpacing = 0;
    public static final int lbResizingTextView_resizeTrigger = 1;
    public static final int lbResizingTextView_resizedPaddingAdjustmentBottom = 2;
    public static final int lbResizingTextView_resizedPaddingAdjustmentTop = 3;
    public static final int lbResizingTextView_resizedTextSize = 4;
    public static final int lbSearchOrbView_searchOrbBrightColor = 0;
    public static final int lbSearchOrbView_searchOrbColor = 1;
    public static final int lbSearchOrbView_searchOrbIcon = 2;
    public static final int lbSearchOrbView_searchOrbIconColor = 3;
    public static final int lbSlide_android_duration = 1;
    public static final int lbSlide_android_interpolator = 0;
    public static final int lbSlide_android_startDelay = 2;
    public static final int lbSlide_lb_slideEdge = 3;
    public static final int lbTimePicker_is24HourFormat = 0;
    public static final int lbTimePicker_useCurrentTime = 3;
    public static final int[] LeanbackGuidedStepTheme = {R.attr.guidanceBreadcrumbStyle, R.attr.guidanceContainerStyle, R.attr.guidanceDescriptionStyle, R.attr.guidanceEntryAnimation, R.attr.guidanceIconStyle, R.attr.guidanceTitleStyle, R.attr.guidedActionCheckedAnimation, R.attr.guidedActionContentWidth, R.attr.guidedActionContentWidthNoIcon, R.attr.guidedActionContentWidthWeight, R.attr.guidedActionContentWidthWeightTwoPanels, R.attr.guidedActionDescriptionMinLines, R.attr.guidedActionDisabledChevronAlpha, R.attr.guidedActionEnabledChevronAlpha, R.attr.guidedActionItemCheckmarkStyle, R.attr.guidedActionItemChevronStyle, R.attr.guidedActionItemContainerStyle, R.attr.guidedActionItemContentStyle, R.attr.guidedActionItemDescriptionStyle, R.attr.guidedActionItemIconStyle, R.attr.guidedActionItemTitleStyle, R.attr.guidedActionPressedAnimation, R.attr.guidedActionTitleMaxLines, R.attr.guidedActionTitleMinLines, R.attr.guidedActionUncheckedAnimation, R.attr.guidedActionUnpressedAnimation, R.attr.guidedActionVerticalPadding, R.attr.guidedActionsBackground, R.attr.guidedActionsBackgroundDark, R.attr.guidedActionsContainerStyle, R.attr.guidedActionsElevation, R.attr.guidedActionsEntryAnimation, R.attr.guidedActionsListStyle, R.attr.guidedActionsSelectorDrawable, R.attr.guidedActionsSelectorHideAnimation, R.attr.guidedActionsSelectorShowAnimation, R.attr.guidedActionsSelectorStyle, R.attr.guidedActionsShadowWidth, R.attr.guidedButtonActionsListStyle, R.attr.guidedButtonActionsWidthWeight, R.attr.guidedStepBackground, R.attr.guidedStepEntryAnimation, R.attr.guidedStepExitAnimation, R.attr.guidedStepHeightWeight, R.attr.guidedStepImeAppearingAnimation, R.attr.guidedStepImeDisappearingAnimation, R.attr.guidedStepKeyline, R.attr.guidedStepReentryAnimation, R.attr.guidedStepReturnAnimation, R.attr.guidedStepTheme, R.attr.guidedStepThemeFlag, R.attr.guidedSubActionsListStyle};
    public static final int[] LeanbackOnboardingTheme = {R.attr.onboardingDescriptionStyle, R.attr.onboardingHeaderStyle, R.attr.onboardingLogoStyle, R.attr.onboardingMainIconStyle, R.attr.onboardingNavigatorContainerStyle, R.attr.onboardingPageIndicatorStyle, R.attr.onboardingStartButtonStyle, R.attr.onboardingTheme, R.attr.onboardingTitleStyle};
    public static final int[] LeanbackTheme = {R.attr.baseCardViewStyle, R.attr.browsePaddingBottom, R.attr.browsePaddingEnd, R.attr.browsePaddingStart, R.attr.browsePaddingTop, R.attr.browseRowsFadingEdgeLength, R.attr.browseRowsMarginStart, R.attr.browseRowsMarginTop, R.attr.browseTitleIconStyle, R.attr.browseTitleTextStyle, R.attr.browseTitleViewLayout, R.attr.browseTitleViewStyle, R.attr.datePickerStyle, R.attr.defaultBrandColor, R.attr.defaultBrandColorDark, R.attr.defaultSearchBrightColor, R.attr.defaultSearchColor, R.attr.defaultSearchIcon, R.attr.defaultSearchIconColor, R.attr.defaultSectionHeaderColor, R.attr.detailsActionButtonStyle, R.attr.detailsDescriptionBodyStyle, R.attr.detailsDescriptionSubtitleStyle, R.attr.detailsDescriptionTitleStyle, R.attr.errorMessageStyle, R.attr.headerStyle, R.attr.headersVerticalGridStyle, R.attr.imageCardViewBadgeStyle, R.attr.imageCardViewContentStyle, R.attr.imageCardViewImageStyle, R.attr.imageCardViewInfoAreaStyle, R.attr.imageCardViewStyle, R.attr.imageCardViewTitleStyle, R.attr.itemsVerticalGridStyle, R.attr.overlayDimActiveLevel, R.attr.overlayDimDimmedLevel, R.attr.overlayDimMaskColor, R.attr.pickerStyle, R.attr.pinPickerStyle, R.attr.playbackControlButtonLabelStyle, R.attr.playbackControlsActionIcons, R.attr.playbackControlsAutoHideTickleTimeout, R.attr.playbackControlsAutoHideTimeout, R.attr.playbackControlsButtonStyle, R.attr.playbackControlsIconHighlightColor, R.attr.playbackControlsTimeStyle, R.attr.playbackMediaItemDetailsStyle, R.attr.playbackMediaItemDurationStyle, R.attr.playbackMediaItemNameStyle, R.attr.playbackMediaItemNumberStyle, R.attr.playbackMediaItemNumberViewFlipperLayout, R.attr.playbackMediaItemNumberViewFlipperStyle, R.attr.playbackMediaItemPaddingStart, R.attr.playbackMediaItemRowStyle, R.attr.playbackMediaItemSeparatorStyle, R.attr.playbackMediaListHeaderStyle, R.attr.playbackMediaListHeaderTitleStyle, R.attr.playbackPaddingEnd, R.attr.playbackPaddingStart, R.attr.playbackProgressPrimaryColor, R.attr.playbackProgressSecondaryColor, R.attr.rowHeaderDescriptionStyle, R.attr.rowHeaderDockStyle, R.attr.rowHeaderStyle, R.attr.rowHorizontalGridStyle, R.attr.rowHoverCardDescriptionStyle, R.attr.rowHoverCardTitleStyle, R.attr.rowsVerticalGridStyle, R.attr.searchOrbViewStyle, R.attr.sectionHeaderStyle, R.attr.timePickerStyle};
    public static final int[] PagingIndicator = {R.attr.arrowBgColor, R.attr.arrowColor, R.attr.arrowRadius, R.attr.dotBgColor, R.attr.dotToArrowGap, R.attr.dotToDotGap, R.attr.lbDotRadius};
    public static final int[] lbBaseCardView = {R.attr.activatedAnimationDuration, R.attr.cardBackground, R.attr.cardForeground, R.attr.cardType, R.attr.extraVisibility, R.attr.infoVisibility, R.attr.selectedAnimationDelay, R.attr.selectedAnimationDuration};
    public static final int[] lbBaseCardView_Layout = {R.attr.layout_viewType};
    public static final int[] lbDatePicker = {android.R.attr.minDate, android.R.attr.maxDate, R.attr.datePickerFormat, R.attr.pickerItemLayout, R.attr.pickerItemTextViewId};
    public static final int[] lbImageCardView = {R.attr.infoAreaBackground, R.attr.lbImageCardViewType};
    public static final int[] lbPicker = {R.attr.pickerItemLayout, R.attr.pickerItemTextViewId};
    public static final int[] lbPinPicker = {R.attr.columnCount, R.attr.pickerItemLayout, R.attr.pickerItemTextViewId};
    public static final int[] lbPlaybackControlsActionIcons = {R.attr.closed_captioning, R.attr.fast_forward, R.attr.high_quality, R.attr.pause, R.attr.picture_in_picture, R.attr.play, R.attr.repeat, R.attr.repeat_one, R.attr.rewind, R.attr.shuffle, R.attr.skip_next, R.attr.skip_previous, R.attr.thumb_down, R.attr.thumb_down_outline, R.attr.thumb_up, R.attr.thumb_up_outline};
    public static final int[] lbResizingTextView = {R.attr.maintainLineSpacing, R.attr.resizeTrigger, R.attr.resizedPaddingAdjustmentBottom, R.attr.resizedPaddingAdjustmentTop, R.attr.resizedTextSize};
    public static final int[] lbSearchOrbView = {R.attr.searchOrbBrightColor, R.attr.searchOrbColor, R.attr.searchOrbIcon, R.attr.searchOrbIconColor};
    public static final int[] lbSlide = {android.R.attr.interpolator, android.R.attr.duration, android.R.attr.startDelay, R.attr.lb_slideEdge};
    public static final int[] lbTimePicker = {R.attr.is24HourFormat, R.attr.pickerItemLayout, R.attr.pickerItemTextViewId, R.attr.useCurrentTime};
}
